### ISSUE TITLE
"Waka" stops working B2.92

### ISSUE THREAD

**Issue by MorrisMwiti** [allista/WakatimeBlender#11]
Hi, 
Waka stopped working in B2.92, when  I try and reload it this, what I am getting!

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\WakaTime.py", line 369, in register
    setup()
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\WakaTime.py", line 293, in setup
    SETTINGS.read(SETTINGS_FILE)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\\\.wakatime.cfg', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Comment by allista** [comment]
This looks like a corrupted config file. Removing it and setting the API key should fix the problem.

Also, I'm working on the v2.0 of the plugin right now, which should also fix the exception you see, allowing the plugin to register fine even in this case.
