### ISSUE TITLE
addon Material Library VX conflict

### ISSUE THREAD

**Issue by zavx0z** [allista/WakatimeBlender#12]
![Screenshot from 2021-05-12 07-38-26](https://user-images.githubusercontent.com/7262706/117919266-5f44ad00-b2f5-11eb-8f25-0cd5bf5095f0.png)

```
Read prefs: /home/zavx0z/.config/blender/2.93/config/userpref.blend
Registered Animation Nodes
[WakaTime] [INFO] Initializing WakaTime plugin v1.1.0
[WakaTime] [INFO] WakatimeBlender is registered
[WakaTime] [INFO] Found Wakatime client.
Warning: class UI_OT_wakatime_api_key_dialog contains a property which should be an annotation!
/home/zavx0z/.config/blender/2.93/scripts/addons/WakaTime.py:371
    assign as a type annotation: UI_OT_wakatime_api_key_dialog.api_key
Read blend: /home/zavx0z/unmanned/microservice/admin/enginei.blend
[WakaTime] [INFO] project-name in WakaTime: admin
/home/zavx0z/.config/blender/2.93/scripts/addons/WakaTime.py:157: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  bpy.app.binary_path_python,
[WakaTime] [ERROR] Error
[WakaTime] [ERROR] wakatime-core output: /home/zavx0z/.wakatime/wakatime-master/wakatime/packages/tzlocal/unix.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while start is not 0:

/home/zavx0z/.config/blender/2.93/scripts/addons/WakaTime.py:157: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  bpy.app.binary_path_python,
invoke lib0
Blender 2.93.0 Alpha (hash 7a608f88a713 built 2021-02-15 00:12:31)
Read prefs: /home/zavx0z/.config/blender/2.93/config/userpref.blend
Exception in module register(): /home/zavx0z/.config/blender/2.93/scripts/addons/VSE_Transform_Tools/__init__.py
Traceback (most recent call last):
  File "/opt/blender-2.93.0-7a608f88a713-linux64/2.93/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/zavx0z/.config/blender/2.93/scripts/addons/VSE_Transform_Tools/__init__.py", line 227, in register
    km = wm.keyconfigs.addon.keymaps.new(name="SequencerPreview", space_type="SEQUENCE_EDITOR", region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'
Registered Animation Nodes
[WakaTime] [INFO] Initializing WakaTime plugin v1.1.0
[WakaTime] [INFO] WakatimeBlender is registered
[WakaTime] [INFO] Found Wakatime client.
Warning: class UI_OT_wakatime_api_key_dialog contains a property which should be an annotation!
/home/zavx0z/.config/blender/2.93/scripts/addons/WakaTime.py:371
    assign as a type annotation: UI_OT_wakatime_api_key_dialog.api_key
Read blend: /home/zavx0z/.config/blender/matlib/sample_materials.blend
[WakaTime] [INFO] project-name in WakaTime: matlib
Unregistered Animation Nodes
[WakaTime] [INFO] Unregistering WakaTime plugin v1.1.0
/home/zavx0z/.config/blender/2.93/scripts/addons/WakaTime.py:157: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  bpy.app.binary_path_python,

````

**Comment by allista** [comment]
This should already be fixed in the current `master` branch.
